# Generate fw_version.h with a build timestamp on every build.
# SCons uses content hashing, so we must change actual file content
# (not just mtime) to force recompilation of main.cpp.
# Works for all three environments — outputs to the correct source dir.
Import("env")
import time

timestamp = time.strftime("%b %d %Y %H:%M:%S")

# Determine output path based on environment
env_name = env["PIOENV"]
if env_name == "rp2040_display":
    path = "src_display/fw_version.h"
elif env_name == "esp32s3_config":
    path = "src_config/fw_version.h"
else:
    path = "src/fw_version.h"

header = f'// Auto-generated by pre_build.py — do not edit\n#define FW_BUILD_TIME "{timestamp}"\n'

try:
    with open(path, "r") as f:
        existing = f.read()
except FileNotFoundError:
    existing = ""

if existing != header:
    with open(path, "w") as f:
        f.write(header)
