# Generate fw_version.h with a build timestamp on every build.
# SCons uses content hashing, so we must change actual file content
# (not just mtime) to force recompilation of main.cpp.
# Works for all three environments — outputs to the correct source dir.
Import("env")
import time
import os

timestamp = time.strftime("%b %d %Y %H:%M:%S")

# Determine output path based on environment
env_name = env["PIOENV"]
if env_name == "rp2040_display":
    path = "src_display/fw_version.h"
elif env_name == "esp32s3_config":
    path = "src_config/fw_version.h"
else:
    path = "src/fw_version.h"

header = f'// Auto-generated by pre_build.py — do not edit\n#define FW_BUILD_TIME "{timestamp}"\n'

try:
    with open(path, "r") as f:
        existing = f.read()
except FileNotFoundError:
    existing = ""

if existing != header:
    with open(path, "w") as f:
        f.write(header)

# ── Patch tinyproto library for PlatformIO compatibility ──
# TinyProtocol.cpp and TinySerialFdLink.cpp reference internal macros
# (FD_BUF_SIZE_EX) that fail to compile. We only need TinyProtocolFd,
# so remove the broken convenience wrappers from all environments.
# Also rename tiny_types.c → tiny_types.cpp so Arduino HAL functions
# (millis, delay) resolve correctly on the earlephilhower RP2040 core.
libdeps_dir = os.path.join(env.subst("$PROJECT_DIR"), ".pio", "libdeps", env_name, "Tiny Protocol", "src")
if os.path.isdir(libdeps_dir):
    for bad_file in [
        "TinyProtocol.cpp",
        os.path.join("link", "TinySerialFdLink.cpp"),
    ]:
        full = os.path.join(libdeps_dir, bad_file)
        if os.path.isfile(full):
            os.remove(full)

    # Rename .c → .cpp and inject #include <Arduino.h> so that
    # millis/delay/etc resolve on the RP2040 earlephilhower core.
    c_file = os.path.join(libdeps_dir, "hal", "tiny_types.c")
    cpp_file = os.path.join(libdeps_dir, "hal", "tiny_types.cpp")
    if os.path.isfile(c_file) and not os.path.isfile(cpp_file):
        os.rename(c_file, cpp_file)
    if os.path.isfile(cpp_file):
        with open(cpp_file, "r") as f:
            content = f.read()
        if "#include <Arduino.h>" not in content:
            content = '#include <Arduino.h>\n' + content
            with open(cpp_file, "w") as f:
                f.write(content)
