"""Lower part is now generated by generate_step_cadquery.py.

Both parts are built from a single combined solid and split with a stepped
cutting surface. Run generate_step_cadquery.py to produce both STEP files.
"""

import subprocess
import sys
from pathlib import Path

script = Path(__file__).resolve().parent / "generate_step_cadquery.py"
sys.exit(subprocess.call([sys.executable, str(script)]))
